assert_lefthook_installed: true

post-merge:
  piped: true
  jobs:
    - name: Mise update
      id: mise-update
      run: mise install
      interactive: true

pre-commit:
  piped: true
  jobs:
    - name: "Run formatters"
      run: mask fmt
      stage_fixed: true
    - name: "Run linters"
      run: mask lint

pre-push:
  parallel: true
  jobs:
    - name: "Run check"
      run: mask check
    - name: "Run tests"
      run: mask test
    - name: "Run audit"
      run: mask audit

commit-msg:
  piped: true
  jobs:
    - name: "Run commit linter"
      run: bun run commitlint --edit {1}
