[tools]
bun = "1.2.14"
"go:github.com/evilmartians/lefthook" = "1.11.13"
markdownlint-cli2 = "0.18.1"
mask = "0.11.6"

[vars]
config_dir = "{{config_root}}/.config"

[env]
CLIPPY_CONF_DIR = "{{vars.config_dir}}"

[tasks.bootstrap]
description = "Bootstrap the project"
run = """
  bun install && \
  lefthook install && \
  cargo bin -i
"""
