[tools]
markdownlint-cli2 = "0.17.2"
gh = "2.72.0"
bun = "1.2.13"
"go:github.com/evilmartians/lefthook" = "1.11.13"

[task_config]
includes = [
  ".config/tasks.md.toml",
  ".config/tasks.rs.toml",
  ".config/tasks.ts.toml",
  ".config/tasks.ex.toml",
  "examples/hungry_goblins/tasks.toml",
  "examples/orcnpie/tasks.toml",
]

[vars]
config_dir = "{{config_root}}/.config"

[env]
CLIPPY_CONF_DIR = "{{vars.config_dir}}"

[tasks.bootstrap]
description = "Bootstrap the project"
run = """
  bun install && \
  lefthook install && \
  cargo install cargo-xwin xwin cargo-audit
"""

[tasks.dev]
description = "Run all development tasks"
run = "bacon dev"

[tasks."dev:impl"]
hide = true
depends = ["fmt", "lint", "test"]
run = "mise run build:examples"

[tasks.fmt]
description = "Run all formatting tasks"
depends = ["fmt:*"]

[tasks.lint]
description = "Run all linting tasks"
depends = ["lint:*"]

[tasks.fix]
description = "Fix all linting problems"
depends = ["fix:*"]

[tasks."lint:spellcheck"]
description = "Run spell check"
run = "bun spellcheck"

[tasks.test]
description = "Run all tests in debug mode"
depends = ["test:debug"]

[tasks."test:debug"]
description = "Run all tests in debug mode"
run = "cargo test"

[tasks."test:release"]
description = "Run all tests in release mode"
run = "cargo test --release"

[tasks."build"]
description = "Build all libraries in debug mode"
depends = ["build:debug", "build:examples"]

[tasks."build:debug:all"]
description = "Build all libraries in release mode"
depends = ["build:debug:*", "examples:debug"]

[tasks."build:release:all"]
description = "Build all libraries in release mode"
depends = ["build:release:*", "examples:release"]

[tasks."build:examples"]
description = "Build all examples in debug mode"
depends = ["examples:debug"]

[tasks."build:examples:all"]
description = "Build all examples"
depends = ["examples:debug", "examples:release"]
