avoid-breaking-exported-api = false
doc-valid-idents = ["OS", "GUI"]
disallowed-names = [
  "foo",
  "bar",
  "baz",
  "quux",
  "util",
  "utils",
  "tool",
  "tools",
]
too-many-arguments-threshold = 10
type-complexity-threshold = 250
enum-variant-size-threshold = 200
allow-indexing-slicing-in-tests = true
